version: 2
jobs:
  build:
    docker:
      - image: andrewstucki/go-terraform
    working_directory: /terraform-provider-circleci
    steps:
      - checkout
      - run:
          environment:
            CGO_ENABLED: 0
            TF_ACC: true
            CIRCLECI_VCS_TYPE: github
            CIRCLECI_ORGANIZATION: andrewstucki
            CIRCLECI_PROJECT: circle-test
          name: Test
          command: |
            go test -cover -v ./...
      - run:
          name: Build
          command: |
            CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -a -o build/terraform-provider-circleci-darwin-amd64
            CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -a -o build/terraform-provider-circleci-linux-amd64
      - run:
          name: Compute checksum of binaries
          command: |
            for binary in build/*; do
              sha256sum -b $binary > $binary.sha256
            done
      - persist_to_workspace:
          root: /terraform-provider-circleci
          paths:
            - build
  release:
    working_directory: /build
    docker:
      - image: golang:1.12.1
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Instal GHR
          command: |
            go get github.com/tcnksm/ghr
      - run:
          name: Publish release
          command: |
            ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete -draft ${CIRCLE_TAG} .

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
